spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 2000
        initialSize: 100
        maxWait: 60000
        minIdle: 10
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 50
        dam:
            name: db1
            url: jdbc:mysql://10.4.249.99:3306/multidb1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&allowMultiQueries=true
            username: root
            password: root
        neuabc:
            url: jdbc:mysql://10.4.249.99:3306/multidb2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&allowMultiQueries=true
            username: root
            password: root


    redis:
        host: 10.4.249.94
        password: 123456
        port: 6380
        lettuce:
            pool:
                max-active: 20
                max-wait: -1
        database: 9


mybatis:
    mapper-locations: classpath*:mapper/**/*.xml


#tk 配置选项
mapper:
    not-empty: false
    identity: MYSQL

logging:
    level:
        tk.mybatis: DEBUG
        com.liang.provider: DEBUG