spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: neuabc_framework
        url: jdbc:mysql://rm-bp15uqp5v5o1gs9x6o.mysql.rds.aliyuncs.com:3306/neuabc_framework3_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&allowMultiQueries=true
        username: neuabc3admin
        password: neuabc3admin*
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 2000
        initialSize: 100
        maxWait: 60000
        minIdle: 10
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 50
    redis:
        enable: true
        database: 1
        host: 10.4.249.94
        pool:
            max-active: 20
        password: 123456
        port: 6379

    rabbitmq:
        addresses: 10.4.249.94:5672
        username: root
        password: root
        virtual-host: /
        publisher-confirms: true
        publisher-returns: true
        template:
              mandatory: true
        listener:
            concurrency: 5
            max-concurrency: 100
            acknowledge-mode: auto


mybatis:
    mapper-locations: classpath*:mapper/**/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


#tk 配置选项
mapper:
    not-empty: false
    identity: MYSQL

logging:
    level:
        tk.mybatis: DEBUG
        com.liang.provider: DEBUG