server:
  port: 8080


spring:
  application:
    name: webfulx
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null



  redis:
    host: 10.4.249.94
    password: root

  datasource:
    url: jdbc:mysql://rm-bp15uqp5v5o1gs9x6o.mysql.rds.aliyuncs.com:3306/neuabc_framework3_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&allowMultiQueries=true
    username: neuabc3admin
    password: neuabc3admin*
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml

