spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        username: root
        url: jdbc:mysql://172.16.62.216:3306/seata?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&allowMultiQueries=true
    cloud:
        alibaba:
            seata:
                tx-service-group: order-seata-group


mybatis:
    mapper-locations: classpath*:mapper/**/*.xml

logging:
    level:
        tk.mybatis: DEBUG
        com.liang.good: DEBUG
        org.springframework.jdbc.core.JdbcTemplate: DEBUG


#阿里分布式事务配置
seata:
    service:
        vgroupMapping:
            #这里的组名my_test_tx_group就是上面已经配置过的
            # seata-server 对应的就是register.conf里的application选项的内容
            order-seata-group: seata-server
        enable-degrade: false
        disable-global-transaction: false
        grouplist:
            seata-server: ${seata-server:172.16.62.216:8091}
