eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/


server:
  port: 8444


spring:
  application:
    name: service-c
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  main:
    allow-bean-definition-overriding: true

  redis:
    host: 10.4.249.94
    password: 123456

  datasource:
    url: jdbc:mysql://10.4.249.94:3306/liang?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    filters: stat
    maxActive: 2000
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 50

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml


# 是否开启日志记录。当开启以后需要配置对应logger的数据库连接配置信息。
tx-lcn:
  logger:
    enabled: false
    driver-class-name: ${spring.datasource.driver-class-name}
    username: root
    password: root
    jdbc-url: jdbc:mysql://10.4.249.94:3306/tx-manager?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&allowMultiQueries=true


logging:
  level:
    com.liang.service_c.dao: DEBUG
    org.mybatis: DEBUG