spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.4.249.94:3306/tx-manager?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&allowMultiQueries=true
    username: root
    password: root


  application:
    name: tx-manager


  redis:
    host: 10.4.249.94
    password: 123456

server:
  port: 7970


tx-lcn:
  logger:
    enabled: true

  manager:
    port: 8070 #TM监听Socket端口. 默认为 ${server.port} - 100
    heart-time: 300000  # 心跳检测时间(ms). 默认为 300000
    dtx-time: 36000 #分布式事务执行总时间(ms). 默认为36000
    admin-key: neuabc #TM后台登陆密码，默认值为codingapi
    seq-len: 12 #雪花算法的sequence位长度，默认为12位.
    ex-url-enabled: false #异常回调开关。开启时请制定ex-url
    ex-url: /provider/email-to/***@**.com #事务异常通知（任何http协议地址。未指定协议时，为TM提供内置功能接口）。默认是邮件通知

logging:
  level:
    com.codingapi: debug
    com.liang: debug
