server:
  port: 8212
logging:
  level:
    com.liang.mq: debug


spring:
  rabbitmq:
    addresses: 172.16.62.192:5672
    username: root
    password: root
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      concurrency: 5
      max-concurrency: 100
      acknowledge-mode: auto